/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_urv_zion_bus_BusJNI */

#ifndef _Included_com_urv_zion_bus_BusJNI
#define _Included_com_urv_zion_bus_BusJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_urv_zion_bus_BusJNI
 * Method:    startLogger
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_urv_zion_bus_BusJNI_startLogger
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     com_urv_zion_bus_BusJNI
 * Method:    stopLogger
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_urv_zion_bus_BusJNI_stopLogger
  (JNIEnv *, jobject);

/*
 * Class:     com_urv_zion_bus_BusJNI
 * Method:    createBus
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_urv_zion_bus_BusJNI_createBus
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_urv_zion_bus_BusJNI
 * Method:    listenBus
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_urv_zion_bus_BusJNI_listenBus
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_urv_zion_bus_BusJNI
 * Method:    sendRawMessage
 * Signature: (Ljava/lang/String;Lcom/urv/zion/bus/BusRawMessage;)I
 */
JNIEXPORT jint JNICALL Java_com_urv_zion_bus_BusJNI_sendRawMessage
  (JNIEnv *, jobject, jstring, jobject);

/*
 * Class:     com_urv_zion_bus_BusJNI
 * Method:    receiveRawMessage
 * Signature: (I)Lcom/urv/zion/bus/BusRawMessage;
 */
JNIEXPORT jobject JNICALL Java_com_urv_zion_bus_BusJNI_receiveRawMessage
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
